name: cmake-actions

on:
  push:
    branches:
      - dev/AST

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev/AST

      - name: Use cmake
        run: cmake --version

      - name: Use flex
        run: sudo apt install flex

      - name: Use bison
        run: sudo apt install bison

      - name: Build
        run: |
          cd ${{ github.workspace }}
          ls -la
          mkdir build && cd build
          cmake ..
